version: '3'
services: 
    web:
        image: nginx
        volumes:
         - ./ws.conf:/etc/nginx/conf.d/default.conf
         - ./build/:/var/www/build/
         - ./taskbit.crt:/etc/nginx/taskbit.crt
         - ./taskbit.key:/etc/nginx/taskbit.key
        ports:
            - "80:80"
            - "443:443"        
        command: /bin/bash -c "exec nginx -g 'daemon off;'"
      